# Lokomotive-specific change.
#
# Bypass Global Network Policy blocking access to EC2 instance metadata
# endpoint by allowing controller pods to connect to everything, as
# other pods can.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ebs-csi-controller-allow-all-egress
spec:
  podSelector:
    matchLabels:
      app: ebs-csi-controller
      {{- include "aws-ebs-csi-driver.selectorLabels" . | nindent 6 }}
  egress:
  - {}
  policyTypes:
  - Egress
