apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-server
  labels:
    k8s-app: admission-webhook-server
spec:
  ports:
    - port: 443
      targetPort: 8080
      name: admission-webhook-server
  selector:
    k8s-app: admission-webhook-server
