## XXX: Lokomotive specific change.
##
## This is a deviation from upstream.
## This file was removed because lokoctl creates namespace with the help of helm library. So this
## file is redundant and can cause installation errors.
